site:
  title: Dev Center Docs
  url: https://docs.devcntr.org
  start_page: home::index.adoc
content:
  sources:
    - url: https://github.com/devcntr-org/docs.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/devcntr.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/antora-dark-theme.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/antora-demo-template.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/antora-extensions-registry.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/antora-themes-site.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/templates.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/devcntr-org/msi-generator.git
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/devcntr-org/antora-dark-theme/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

